# JourneyPatternID is a combination of Variant and Direction

In [47]:
import pandas as pd
from datetime import datetime, timedelta

import matplotlib.pyplot as plt
%matplotlib inline

## Import 15 Timetable

In [137]:
timetable = pd.read_csv("bus_data/static_data/master_timetable.csv")

In [94]:
#reassign columns to remove leading whitespace from variant column and name departure index
timetable.columns = ['departure_index', 'variant', 'day', 'departure', 'direction', 'line']

In [95]:
weekdayfifteentimetable = timetable.loc[(timetable['line'] == "15") & (timetable['day'] == "weekday")]
weekdayfifteentimetable.variant.value_counts()

 c    3
Name: variant, dtype: int64

In [96]:
saturdayfifteentimetable = timetable.loc[(timetable['line'] == "15") & (timetable['day'] == "saturday")]
saturdayfifteentimetable.variant.value_counts()

 c    3
Name: variant, dtype: int64

In [97]:
sundayfifteentimetable = timetable.loc[(timetable['line'] == "15") & (timetable['day'] == "sunday")]
sundayfifteentimetable.variant.value_counts()

 c    2
Name: variant, dtype: int64

#### Refine by Direction

In [103]:
directions = (timetable.loc[(timetable['line'] == "15")]).direction.unique()
directions

array(['From Ballycullen Towards Clongriffin',
       'From Clongriffin Towards Ballycullen'], dtype=object)

In [108]:
northbound_weekdayfifteentimetable = weekdayfifteentimetable.loc[(weekdayfifteentimetable['direction'] == directions[0])]
northbound_weekdayfifteentimetable.reset_index(inplace=True)

In [128]:
northbound_weekdayfifteentimetable

,index,departure_index,variant,day,departure,direction,line
0,4422,0,NaN,weekday,6:00,From Ballycullen Towards Clongriffin,15
1,4423,1,NaN,weekday,6:10,From Ballycullen Towards Clongriffin,15
2,4424,2,NaN,weekday,6:20,From Ballycullen Towards Clongriffin,15
3,4425,3,NaN,weekday,6:30,From Ballycullen Towards Clongriffin,15
4,4426,4,NaN,weekday,6:40,From Ballycullen Towards Clongriffin,15
5,4427,5,NaN,weekday,6:50,From Ballycullen Towards Clongriffin,15
6,4428,6,NaN,weekday,7:00,From Ballycullen Towards Clongriffin,15
7,4429,7,NaN,weekday,7:12,From Ballycullen Towards Clongriffin,15
8,4430,8,NaN,weekday,7:25,From Ballycullen Towards Clongriffin,15
9,4431,9,NaN,weekday,7:35,From Ballycullen Towards Clongriffin,15
10,4432,10,NaN,weekday,7:45,From Ballycullen Towards Clongriffin,15
11,4433,11,NaN,weekday,7:53,From Ballycullen Towards Clongriffin,15
12,4434,12,NaN,weekday,8:00,From Ballycullen Towards Clongriffin,15
13,4435,13,NaN,weekday,8:07,From Ballycullen Towards Clongriffin,15
14,4436,14,NaN,weekday,8:15,From Ballycullen Towards Clongriffin,15
15,4437,15,NaN,weekday,8:25,From Ballycullen Towards Clongriffin,15
16,4438,16,NaN,weekday,8:40,From Ballycullen Towards Clongriffin,15
17,4439,17,NaN,weekday,8:50,From Ballycullen Towards Clongriffin,15
18,4440,18,NaN,weekday,9:00,From Ballycullen Towards Clongriffin,15
19,4441,19,NaN,weekday,9:10,From Ballycullen Towards Clongriffin,15
20,4442,20,NaN,weekday,9:20,From Ballycullen Towards Clongriffin,15
21,4443,21,NaN,weekday,9:30,From Ballycullen Towards Clongriffin,15
22,4444,22,NaN,weekday,9:40,From Ballycullen Towards Clongriffin,15
23,4445,23,NaN,weekday,9:50,From Ballycullen Towards Clongriffin,15
24,4446,24,NaN,weekday,10:00,From Ballycullen Towards Clongriffin,15
25,4447,25,NaN,weekday,10:10,From Ballycullen Towards Clongriffin,15
26,4448,26,NaN,weekday,10:20,From Ballycullen Towards Clongriffin,15
27,4449,27,NaN,weekday,10:30,From Ballycullen Towards Clongriffin,15
28,4450,28,NaN,weekday,10:40,From Ballycullen Towards Clongriffin,15
29,4451,29,NaN,weekday,10:50,From Ballycullen Towards Clongriffin,15
...,...,...,...,...,...,...,...
62,4484,62,NaN,weekday,16:20,From Ballycullen Towards Clongriffin,15
63,4485,63,NaN,weekday,16:30,From Ballycullen Towards Clongriffin,15
64,4486,64,NaN,weekday,16:40,From Ballycullen Towards Clongriffin,15
65,4487,65,NaN,weekday,16:50,From Ballycullen Towards Clongriffin,15
66,4488,66,NaN,weekday,17:00,From Ballycullen Towards Clongriffin,15
67,4489,67,NaN,weekday,17:10,From Ballycullen Towards Clongriffin,15
68,4490,68,NaN,weekday,17:20,From Ballycullen Towards Clongriffin,15
69,4491,69,NaN,weekday,17:30,From Ballycullen Towards Clongriffin,15
70,4492,70,NaN,weekday,17:40,From Ballycullen Towards Clongriffin,15
71,4493,71,NaN,weekday,17:50,From Ballycullen Towards Clongriffin,15
72,4494,72,NaN,weekday,18:00,From Ballycullen Towards Clongriffin,15
73,4495,73,NaN,weekday,18:10,From Ballycullen Towards Clongriffin,15
74,4496,74,NaN,weekday,18:20,From Ballycullen Towards Clongriffin,15
75,4497,75,NaN,weekday,18:30,From Ballycullen Towards Clongriffin,15
76,4498,76,NaN,weekday,18:40,From Ballycullen Towards Clongriffin,15
77,4499,77,NaN,weekday,18:50,From Ballycullen Towards Clongriffin,15
78,4500,78,NaN,weekday,19:00,From Ballycullen Towards Clongriffin,15
79,4501,79,NaN,weekday,19:20,From Ballycullen Towards Clongriffin,15
80,4502,80,NaN,weekday,19:40,From Ballycullen Towards Clongriffin,15
81,4503,81,NaN,weekday,20:00,From Ballycullen Towards Clongriffin,15
82,4504,82,NaN,weekday,20:20,From Ballycullen Towards Clongriffin,15
83,4505,83,NaN,weekday,20:40,From Ballycullen Towards Clongriffin,15
84,4506,84,NaN,weekday,21:00,From Ballycullen Towards Clongriffin,15
85,4507,85,NaN,weekday,21:20,From Ballycullen Towards Clongriffin,15
86,4508,86,NaN,weekday,21:40,From Ballycullen Towards Clongriffin,15
87,4509,87,NaN,weekday,22:00,From Ballycullen Towards Clongriffin,15
88,4510,88,NaN,weekday,22:20,From Ballycullen Towards Clongriffin,15
89,4511,89,NaN,weekday,22:40,From Ballycullen Towards Clongriffin,15
90,4512,90,NaN,weekday,23:00,From Ballycullen Towards Clongriffin,15
91,4513,91,c,weekday,23:20,From Ballycullen Towards Clongriffin,15

In [129]:
southbound_weekdayfifteentimetable = weekdayfifteentimetable.loc[(weekdayfifteentimetable['direction'] == directions[0])]
southbound_weekdayfifteentimetable.reset_index(inplace=True)

In [131]:
southbound_weekdayfifteentimetable.shape

(92, 7)

## Import 15 Data

In [48]:
fifteen = pd.read_csv("bus_data/line_data/15.csv")
fifteen.columns = ["Timestamp", "LineID", "JourneyPatternID", "TimeFrame", 
              "VehicleJourneyID", "Lon", "Lat", "VehicleID", "StopID", 
              "AtStop", "HumanTime", "Day", "Hour", "Runtime"]

In [77]:
fifteen['HumanTime'] = pd.to_datetime(fifteen['HumanTime'])

#### number of journey pattern ids should equal number of directions + variations on each direction

In [78]:
journeypatterns = list(fifteen.JourneyPatternID.unique())

In [79]:
journeypatterns

[1, 1001, 1002, 2]

In [80]:
#Monday is 0, Sunday is 6
def get_day(x):
    if x.weekday() == 5:
        return "saturday"
    elif x.weekday() == 6:
        return "sunday"
    else:
        return "weekday"
    
fifteen["day"] = fifteen['HumanTime'].apply(get_day)

In [83]:
sunday = fifteen.loc[fifteen['day'] == "sunday"]
saturday = fifteen.loc[fifteen['day'] == "saturday"]
weekday = fifteen.loc[fifteen['day'] == "weekday"]

In [84]:
weekday.JourneyPatternID.value_counts()

1       110972
1001    102739
1002       526
2          158
Name: JourneyPatternID, dtype: int64

Extract Single Day and JourneyPatternID

In [86]:
saturday.JourneyPatternID.value_counts()

1       12157
1001    11304
1002      166
2          42
Name: JourneyPatternID, dtype: int64

In [87]:
sunday.JourneyPatternID.value_counts()

1       7332
1001    6838
1002      31
2         22
Name: JourneyPatternID, dtype: int64

Therefore there are 2 directions and 2 variations everyday

In [115]:
tuesday = fifteen.loc[(fifteen['TimeFrame'] == "2012-11-07")]

1       2944
1001    2540
1002      13
2          2
Name: JourneyPatternID, dtype: int64

In [118]:
tuesday_trips = tuesday.drop_duplicates("VehicleJourneyID", keep='first', inplace=False)
print("total number of trips on a single tuesday is:")
tuesday_trips.JourneyPatternID.value_counts().sum()

total number of trips on a single tuesday is:

183

In [126]:
print("which is almost the name as the number there ought to be on a single day:")
weekdayfifteentimetable.shape[0]

which is almost the name as the number there ought to be on a single day:

184

In [120]:
tuesday_trips = tuesday.drop_duplicates("VehicleJourneyID", keep='first', inplace=False)
print("But the JourneyPattern ID counts of those trips on a single tuesday are not evely divided:")
tuesday_trips.JourneyPatternID.value_counts()

But the JourneyPattern ID counts of those trips on a single tuesday are not evely divided:

1       132
1001     49
1002      1
2         1
Name: JourneyPatternID, dtype: int64

##### The JourneyPatternID "1" has too high a count to describe a single direction, it must describe 2.

In [132]:
tuesday_trips.JourneyPatternID.value_counts().sum()

183

In [136]:
tuesday_trips_oneway = tuesday_trips.loc[(tuesday_trips['JourneyPatternID'] == 1)]
tuesday_trips_oneway

,Timestamp,LineID,JourneyPatternID,TimeFrame,VehicleJourneyID,Lon,Lat,VehicleID,StopID,AtStop,HumanTime,Day,Hour,Runtime,day
5482,1352268002000000,15,1,2012-11-07,5891,-6.150383,53.402901,33621,6318,1,2012-11-07 06:00:02,2,6,0,weekday
5494,1352268883000000,15,1,2012-11-07,5899,-6.173066,53.402138,33498,4595,1,2012-11-07 06:14:43,2,6,341,weekday
5511,1352269408000000,15,1,2012-11-07,5902,-6.162333,53.401539,33499,6320,1,2012-11-07 06:23:28,2,6,281,weekday
5532,1352270072000000,15,1,2012-11-07,5912,-6.173066,53.402138,33622,4595,1,2012-11-07 06:34:32,2,6,361,weekday
5556,1352270428000000,15,1,2012-11-07,5920,-6.153783,53.402687,33502,6319,1,2012-11-07 06:40:28,2,6,59,weekday
5593,1352271050000000,15,1,2012-11-07,5930,-6.153783,53.402687,33515,6319,1,2012-11-07 06:50:50,2,6,0,weekday
5631,1352271645000000,15,1,2012-11-07,5937,-6.153783,53.402687,33340,6319,1,2012-11-07 07:00:45,2,7,260,weekday
5657,1352272012000000,15,1,2012-11-07,5945,-6.151516,53.402699,33546,6318,1,2012-11-07 07:06:52,2,7,0,weekday
5742,1352273144000000,15,1,2012-11-07,5952,-6.153783,53.402687,33547,6319,1,2012-11-07 07:25:44,2,7,121,weekday
5807,1352273810000000,15,1,2012-11-07,5892,-6.323367,53.271568,33621,6282,1,2012-11-07 07:36:50,2,7,0,weekday
5827,1352274023000000,15,1,2012-11-07,5844,-6.173066,53.402138,33210,4595,1,2012-11-07 07:40:23,2,7,639,weekday
5865,1352274382000000,15,1,2012-11-07,5859,-6.157236,53.402843,33006,7246,1,2012-11-07 07:46:22,2,7,270,weekday
5923,1352274972000000,15,1,2012-11-07,5782,-6.157236,53.402843,33470,7246,1,2012-11-07 07:56:12,2,7,742,weekday
5952,1352275250000000,15,1,2012-11-07,5779,-6.153783,53.402687,33469,6319,1,2012-11-07 08:00:50,2,8,659,weekday
5957,1352275311000000,15,1,2012-11-07,5913,-6.320583,53.271866,33622,6282,1,2012-11-07 08:01:51,2,8,0,weekday
6007,1352275728000000,15,1,2012-11-07,5785,-6.157236,53.402843,33471,7246,1,2012-11-07 08:08:48,2,8,0,weekday
6053,1352276199000000,15,1,2012-11-07,5793,-6.157236,53.402843,33523,7246,1,2012-11-07 08:16:39,2,8,181,weekday
6110,1352276724000000,15,1,2012-11-07,5801,-6.153783,53.402687,33475,6319,1,2012-11-07 08:25:24,2,8,178,weekday
6114,1352276753000000,15,1,2012-11-07,5931,-6.328667,53.271416,33515,6282,1,2012-11-07 08:25:53,2,8,0,weekday
6220,1352277708000000,15,1,2012-11-07,5811,-6.157236,53.402843,33009,7246,1,2012-11-07 08:41:48,2,8,0,weekday
6239,1352277886000000,15,1,2012-11-07,5938,-6.328717,53.271450,33340,6282,1,2012-11-07 08:44:46,2,8,0,weekday
6287,1352278290000000,15,1,2012-11-07,5818,-6.157236,53.402843,33208,7246,1,2012-11-07 08:51:30,2,8,397,weekday
6328,1352278598000000,15,1,2012-11-07,5946,-6.328913,53.271709,33546,6282,1,2012-11-07 08:56:38,2,8,0,weekday
6357,1352278865000000,15,1,2012-11-07,5828,-6.157236,53.402843,33255,7246,1,2012-11-07 09:01:05,2,9,0,weekday
6381,1352279083000000,15,1,2012-11-07,5953,-6.328383,53.271217,33547,6282,1,2012-11-07 09:04:43,2,9,0,weekday
6433,1352279561000000,15,1,2012-11-07,5835,-6.162333,53.401539,33254,6320,1,2012-11-07 09:12:41,2,9,322,weekday
6448,1352279686000000,15,1,2012-11-07,5845,-6.328567,53.271366,33210,6282,1,2012-11-07 09:14:46,2,9,0,weekday
6527,1352280283000000,15,1,2012-11-07,5860,-6.328516,53.271282,33006,6282,1,2012-11-07 09:24:43,2,9,0,weekday
6659,1352281490000000,15,1,2012-11-07,5780,-6.325600,53.271233,33469,6282,1,2012-11-07 09:44:50,2,9,0,weekday
6669,1352281615000000,15,1,2012-11-07,5901,-6.151417,53.402832,33498,6318,1,2012-11-07 09:46:55,2,9,0,weekday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9462,1352309687000000,15,1,2012-11-07,5833,-6.328700,53.271465,33255,6282,1,2012-11-07 17:34:47,2,17,0,weekday
9498,1352310072000000,15,1,2012-11-07,5951,-6.157236,53.402843,33546,7246,1,2012-11-07 17:41:12,2,17,117,weekday
9520,1352310284000000,15,1,2012-11-07,5840,-6.328617,53.271385,33254,6282,1,2012-11-07 17:44:44,2,17,0,weekday
9604,1352311034000000,15,1,2012-11-07,5850,-6.162333,53.401539,33210,6320,1,2012-11-07 17:57:14,2,17,0,weekday
9656,1352311473000000,15,1,2012-11-07,5858,-6.331206,53.275925,24605,6326,1,2012-11-07 18:04:33,2,18,0,weekday
9728,1352312053000000,15,1,2012-11-07,5865,-6.163521,53.399288,33006,4594,1,2012-11-07 18:14:13,2,18,0,weekday
9801,1352312555000000,15,1,2012-11-07,5876,-6.162333,53.401539,24621,6320,1,2012-11-07 18:22:35,2,18,0,weekday
9872,1352313148000000,15,1,2012-11-07,5888,-6.157236,53.402843,33020,7246,1,2012-11-07 18:32:28,2,18,0,weekday
9958,1352313943000000,15,1,2012-11-07,5791,-6.162333,53.401539,33384,6320,1,2012-11-07 18:45:43,2,18,0,weekday
10018,1352314396000000,15,1,2012-11-07,5799,-6.163521,53.399288,33523,4594,1,2012-11-07 18:53:16,2,18,0,weekday
10070,1352314993000000,15,1,2012-11-07,5807,-6.162333,53.401539,33475,6320,1,2012-11-07 19:03:13,2,19,0,weekday
10154,1352315830000000,15,1,2012-11-07,5944,-6.328533,53.271301,33174,6282,1,2012-11-07 19:17:10,2,19,0,weekday
10185,1352316178000000,15,1,2012-11-07,5824,-6.162333,53.401539,33208,6320,1,2012-11-07 19:22:58,2,19,157,weekday
10251,1352316884000000,15,1,2012-11-07,5959,-6.328583,53.271385,33553,6282,1,2012-11-07 19:34:44,2,19,0,weekday
10294,1352317491000000,15,1,2012-11-07,5851,-6.328467,53.271282,33210,6282,1,2012-11-07 19:44:51,2,19,0,weekday
10302,1352317564000000,15,1,2012-11-07,5841,-6.162333,53.401539,33254,6320,1,2012-11-07 19:46:04,2,19,464,weekday
10410,1352319443000000,15,1,2012-11-07,5884,-6.219658,53.374786,33203,664,1,2012-11-07 20:17:23,2,20,0,weekday
10485,1352320484000000,15,1,2012-11-07,5808,-6.328533,53.271317,33475,6282,1,2012-11-07 20:34:44,2,20,0,weekday
10488,1352320531000000,15,1,2012-11-07,5910,-6.151417,53.402832,33499,6318,1,2012-11-07 20:35:31,2,20,0,weekday
10527,1352321451000000,15,1,2012-11-07,5964,-6.258538,53.345268,33513,348,1,2012-11-07 20:50:51,2,20,0,weekday
10558,1352322119000000,15,1,2012-11-07,5928,-6.153783,53.402687,33502,6319,1,2012-11-07 21:01:59,2,21,387,weekday
10642,1352323627000000,15,1,2012-11-07,5960,-6.181091,53.401699,33553,4563,1,2012-11-07 21:27:07,2,21,456,weekday
10657,1352324090000000,15,1,2012-11-07,5885,-6.328683,53.271435,33203,6282,1,2012-11-07 21:34:50,2,21,0,weekday
10670,1352324488000000,15,1,2012-11-07,5867,-6.157236,53.402843,33006,7246,1,2012-11-07 21:41:28,2,21,0,weekday
10709,1352325275000000,15,1,2012-11-07,5965,-6.328533,53.271332,33513,6282,1,2012-11-07 21:54:35,2,21,0,weekday
10730,1352325931000000,15,1,2012-11-07,5890,-6.181091,53.401699,33020,4563,1,2012-11-07 22:05:31,2,22,642,weekday
10786,1352327098000000,15,1,2012-11-07,5809,-6.163521,53.399288,33475,4594,1,2012-11-07 22:24:58,2,22,0,weekday
10839,1352328276000000,15,1,2012-11-07,5826,-6.173066,53.402138,33208,4595,1,2012-11-07 22:44:36,2,22,600,weekday
10888,1352329464000000,15,1,2012-11-07,5843,-6.173066,53.402138,33254,4595,1,2012-11-07 23:04:24,2,23,359,weekday
10913,1352330076000000,15,1,2012-11-07,5868,-6.328633,53.271366,33006,6282,1,2012-11-07 23:14:36,2,23,0,weekday

### It is very difficult to infer which of these is in which direction

was there originally a direction collumn which was dropped which could be resused?